apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cassandra-deployment
  name: cassandra-deployment
  namespace: gitlab-managed-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-deployment
  template:
    metadata:
      labels:
        app: cassandra-deployment
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
    spec:
      containers:
        - image: cassandra:4.0-beta4
          imagePullPolicy: Always
          name: cassandra
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 15
            periodSeconds: 20
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME", "NET_RAW"]
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab-managed-apps
  labels:
    app: cassandra-deployment
  name: cassandra-service
spec:
  ports:
    - port: 9042
  selector:
    app: cassandra-deployment
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vms-deployment
  name: vms-deployment
  namespace: gitlab-managed-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vms-deployment
  template:
    metadata:
      labels:
        app: vms-deployment
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
    spec:
      containers:
      - image: registry.gitlab.com/lamoboos223/visitor-management-system:master
        name: vms-deployment
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME", "NET_RAW"]
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab-managed-apps
  labels:
    app: vms-deployment
  name: vms-service
spec:
  ports:
    - port: 9090
  selector:
    app: vms-deployment
  type: LoadBalancer