apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appointmentsbooking-deployment
  name: appointmentsbooking-deployment
  namespace: gitlab-managed-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointmentsbooking-deployment
  template:
    metadata:
      labels:
        app: appointmentsbooking-deployment
    spec:
      containers:
        - name: appointmentsbooking-deployment
          image: registry.gitlab.com/lamoboos223/appointments-booking:master
          ports:
            - containerPort: 9090
          imagePullPolicy: Always
#        imagePullSecrets:
#          - name: regcred
#        resources:
#          requests:
#            memory: "64Mi"
#            cpu: "250m"
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
#          readinessProbe:
#            tcpSocket:
#              port: 9090
#            initialDelaySeconds: 5
#            periodSeconds: 10
#          livenessProbe:
#            tcpSocket:
#              port: 9090
#            initialDelaySeconds: 15
#            periodSeconds: 20
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME", "NET_RAW"]
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab-managed-apps
  labels:
    app: appointmentsbooking-deployment
  name: appointmentsbooking-service
spec:
  ports:
    - port: 9090
  selector:
    app: appointmentsbooking-deployment
  type: LoadBalancer