apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cassandra-deployment
  name: cassandra-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-deployment
  template:
    metadata:
      labels:
        app: cassandra-deployment
    spec:
      containers:
        - image: cassandra
          imagePullPolicy: Always
          name: cassandra
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-deployment
  name: cassandra-service
spec:
  ports:
    - port: 9042
  selector:
    app: cassandra-deployment
  type: LoadBalancer
