apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appointmentsbooking-deployment
  name: appointmentsbooking-deployment
  namespace: gitlab-managed-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointmentsbooking-deployment
  template:
    metadata:
      labels:
        app: appointmentsbooking-deployment
    spec:
      containers:
        - name: appointmentsbooking-deployment
          image: registry.gitlab.com/lamoboos223/appointments-booking:master
          ports:
            - containerPort: 9090
          env:
          - name: CONTACT_POINTS
            value: 172.17.0.3,172.25.0.2,127.0.0.1,10.84.0.87
#            valueFrom:
#              secretKeyRef:
#                name: appointmentsbooking-secret
#                key: CONTACT_POINTS
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab-managed-apps
  labels:
    app: appointmentsbooking-deployment
  name: appointmentsbooking-service
spec:
  ports:
    - port: 9090
  selector:
    app: appointmentsbooking-deployment
  type: LoadBalancer