version: '3.1'
services:
  app:
    container_name: app
    build: .
    ports:
      - "9090:9090"
    restart: always
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7199:7199"