apiVersion: v1
kind: ConfigMap
metadata:
  namespace: gitlab-managed-apps
  name: kafka-configmap
data:
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_CREATE_TOPICS: "appointments_booking_topic:1:1"
  KAFKA_ADVERTISED_HOST_NAME: kafka-service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: gitlab-managed-apps
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zoo1
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab-managed-apps
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab-managed-apps
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka
    id: "0"
  # type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
  namespace: gitlab-managed-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "30718"
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_ADVERTISED_HOST_NAME
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_ZOOKEEPER_CONNECT
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_CREATE_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_CREATE_TOPICS
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            # - name: KAFKA_ADVERTISED_LISTENERS
            #   value: PLAINTEXT://kafka-service:9092
