spring:
  data:
    cassandra:
      contact-points: 172.17.0.3,172.25.0.2,127.0.0.1,34.123.73.243
      keyspace-name: visitorkeyspace
      schema-action: CREATE_IF_NOT_EXISTS
#grpc:
#  server:
#    security:
#      enabled: true
#      certificate-chain: file:src/main/resources/server.crt
#      private-key: file:src/main/resources/server.key
