spring:
  data:
    cassandra:
      contact-points: 127.0.0.1
      keyspace-name: visitorkeyspace
      schema-action: CREATE_IF_NOT_EXISTS
#grpc:
#  server:
#    security:
#      enabled: true
#      certificate-chain: file:src/main/resources/server.crt
#      private-key: file:src/main/resources/server.key
