spring:
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "com.lama.appointmentsbooking.model"
      bootstarp-servers: kafka-service:9092
      group-id: "appointments_booking_group_id"
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstarp-servers: kafka-service:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    cassandra:
      contact-points: cassandra-service
      keyspace-name: visitorkeyspace
      schema-action: CREATE_IF_NOT_EXISTS
#grpc:
#  server:
#    security:
#      enabled: true
#      certificate-chain: file:src/main/resources/server.crt
#      private-key: file:src/main/resources/server.key
