apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: gitlab-managed-apps
  labels:
    k8s-app: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: elasticsearch
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
    spec:
      containers:
        - image: elasticsearch:6.8.4
          name: elasticsearch
          ports:
            - containerPort: 9200
              name: db
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - name: elasticsearch
              mountPath: /data
          env:
            - name: "NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: elasticsearch
          emptyDir: {}
      initContainers:
        - image: alpine:3.6
          command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
          name: elasticsearch-init
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: gitlab-managed-apps
  labels:
    k8s-app: elasticsearch
spec:
  type: LoadBalancer
  ports:
    - port: 9200
      protocol: TCP
      targetPort: db
  selector:
    k8s-app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: gitlab-managed-apps
  labels:
    k8s-app: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
        - name: kibana-logging
          image: docker.elastic.co/kibana/kibana-oss:6.8.4
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
          ports:
            - containerPort: 5601
              name: ui
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: gitlab-managed-apps
  labels:
    k8s-app: kibana-logging
    kubernetes.io/name: "Kibana"
spec:
  type: LoadBalancer
  ports:
    - port: 5601
      protocol: TCP
      targetPort: ui
  selector:
    k8s-app: kibana-logging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: gitlab-managed-apps
  labels:
    k8s-app: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: apm-server
  template:
    metadata:
      labels:
        k8s-app: apm-server
    spec:
      containers:
        - name: apm-server
          image: docker.elastic.co/apm/apm-server:6.8.4
          env:
            - name: OUTPUT_ELASTICSEARCH_HOSTS
              value: http://localhost:9200
          ports:
            - containerPort: 8200
              name: apm-port
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: gitlab-managed-apps
  labels:
    k8s-app: apm-server
spec:
  type: LoadBalancer
  ports:
    - port: 8200
  selector:
    k8s-app: apm-server
