apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appointmentsbooking-deployment
  name: appointmentsbooking-deployment
  namespace: gitlab-managed-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointmentsbooking-deployment
  template:
    metadata:
      labels:
        app: appointmentsbooking-deployment
    spec:
      containers:
        - name: appointmentsbooking-deployment
          image: registry.gitlab.com/lamoboos223/appointments-booking:master
          envFrom:
            - configMapRef:
                name: app-env
          ports:
            - containerPort: 9090
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab-managed-apps
  labels:
    app: appointmentsbooking-deployment
  name: appointmentsbooking-service
spec:
  ports:
    - port: 9090
  selector:
    app: appointmentsbooking-deployment
  type: LoadBalancer