apiVersion: v1
kind: ConfigMap
metadata:
  namespace: gitlab-managed-apps
  name: kafka-configmap
data:
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_CREATE_TOPICS: "appointmentsbookingtopic:1:1"
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab-managed-apps
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka
    id: "0"
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: gitlab-managed-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 127.0.0.1
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_ZOOKEEPER_CONNECT
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_CREATE_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_CREATE_TOPICS
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
#            - name: KAFKA_ADVERTISED_LISTENERS
#              value: PLAINTEXT://localhost:9092

